// src/svelte/Form/Form.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { HTMLFormAttributes } from "svelte/elements";
	import { cx } from "../../shared/cx.js";

	type FormProps = HTMLFormAttributes & {
		classes?: string[];
		onsubmit?: (event: SubmitEvent) => void;
		children?: Snippet;
	};

	let {
		classes,
		onsubmit,
		children,
		...rest
	}: FormProps = $props();

	const handleSubmit = (event: SubmitEvent) => {
		if (!onsubmit) return;
		event.preventDefault();
		onsubmit(event);
	};
</script>

<form
	class={cx(classes) || undefined}
	onsubmit={onsubmit ? handleSubmit : undefined}
	{...rest}
>
	{@render children?.()}
</form>

// lib/Form/Form.tsx
import type { FormEventHandler } from "react";

import type { StandardProps } from "@/Types";

type FormProps = {
	onSubmit?: FormEventHandler;
	method?: string;
	action?: string;
} & StandardProps;

export const Form = (props: FormProps) => {
	return (
		<form
			className={`${props.classes && props.classes.length > 0 ? props.classes?.join(" ") : ""}`}
			{...(props.onSubmit && {
				onSubmit: (evt) => {
					if (!props.onSubmit) return;
					evt.preventDefault();
					props.onSubmit(evt);
				},
			})}
			{...(props.method && { method: props.method })}
			{...(props.action && { action: props.action })}
		>
			{props.children}
		</form>
	);
};
