// src/react/server/Text/Link.tsx
import rawClasses from "../../../shared/styles/components/text.module.css";
import { cx } from "../../../utils/cx.ts";
import { themed } from "../../../utils/headless.ts";
import type { StandardProps } from "../Types/general.ts";

const classes = themed(rawClasses);

type LinkProps = {
	href: string;
	target?: string;
	rel?: string;
};

/**
 * Renders a styled anchor (`<a>`) element with customizable classes, href, target, and rel attributes.
 *
 * @param props - The properties for the Link component.
 * @param props.href - The URL to which the link points.
 * @param props.children - The content to be displayed inside the link.
 * @param props.classes - Optional additional CSS class names to apply to the link.
 * @param props.target - Specifies where to open the linked document. Defaults to "_parent".
 * @param props.rel - Specifies the relationship of the target object to the link object. Defaults to "noopener noreferrer".
 *
 * @returns A React anchor element with the specified properties and children.
 */
export const Link = (props: StandardProps & LinkProps) => {
	const { rel = "noopener noreferrer", target = "_parent" } = props;

	return (
		<a
			className={cx(classes.a, props.classes)}
			href={props.href}
			target={target}
			rel={rel}
		>
			{props.children}
			{target === "_blank" && (
				<span className="sr-only"> (opens in new tab)</span>
			)}
		</a>
	);
};

// src/svelte/Text/Link.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import { cx } from "../../shared/cx.js";
	import { themed } from "../../shared/headless.js";
	import rawClasses from "../../shared/styles/components/text.module.css";

	const classes = themed(rawClasses);

	type LinkProps = {
		href: string;
		target?: string;
		rel?: string;
		classes?: string[];
		children?: Snippet;
	};

	let {
		href,
		target = "_parent",
		rel = "noopener noreferrer",
		classes: extraClasses,
		children,
	}: LinkProps = $props();
</script>

<a class={cx(classes.a, extraClasses)} {href} {target} {rel}>
	{@render children?.()}
	{#if target === "_blank"}
		<span class="sr-only"> (opens in new tab)</span>
	{/if}
</a>
