// src/svelte/Text/Link.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import { cx } from "../../shared/cx.js";
	import { themed } from "../../shared/headless.js";
	import rawClasses from "../../shared/styles/components/text.module.css";

	const classes = themed(rawClasses);

	type LinkProps = {
		href: string;
		target?: string;
		rel?: string;
		classes?: string[];
		children?: Snippet;
	};

	let {
		href,
		target = "_parent",
		rel = "noopener noreferrer",
		classes: extraClasses,
		children,
	}: LinkProps = $props();
</script>

<a class={cx(classes.a, extraClasses)} {href} {target} {rel}>
	{@render children?.()}
	{#if target === "_blank"}
		<span class="sr-only"> (opens in new tab)</span>
	{/if}
</a>

// lib/Text/Link.tsx
import type { StandardProps } from "@/Types/general";

import classes from "./styles.module.css";

type LinkProps = {
	href: string;
	target?: string;
	rel?: string;
};

export const Link = (props: StandardProps & LinkProps) => {
	const { rel = "noopener noreferrer", target = "_parent" } = props;

	return (
		<a
			className={`${classes.a}${
				props.classes && props.classes.length > 0
					? ` ${props.classes.join(" ")}`
					: ""
			}`}
			href={props.href}
			target={target}
			rel={rel}
		>
			{props.children}
		</a>
	);
};
